import { BrainCircuit, ShieldCheck, Wrench } from "lucide-react";
import type { AgentLayer, AgentStatus } from "./types";

export const agentLayerMeta: Record<
  AgentLayer,
  { label: string; description: string; icon: typeof BrainCircuit; tone: string }
> = {
  decision: {
    label: "决策层",
    description: "发现、分析与策略生成",
    icon: BrainCircuit,
    tone: "teal",
  },
  review: {
    label: "审核层",
    description: "安全、工程与经济审核",
    icon: ShieldCheck,
    tone: "amber",
  },
  execution: {
    label: "执行层",
    description: "资源编排与现场执行",
    icon: Wrench,
    tone: "blue",
  },
};

export const agentStatusLabel: Record<AgentStatus, string> = {
  idle: "空闲",
  thinking: "分析中",
  working: "工作中",
  waiting: "等待中",
  reviewing: "审核中",
  failed: "失败",
  offline: "离线",
};

const agentNames: Readonly<Record<string, string>> = {
  "agent-operations-coordinator": "运营协调 Agent",
  "agent-scada-analysis": "SCADA 分析 Agent",
  "agent-vibration-diagnosis": "振动诊断 Agent",
  "agent-structural-health": "结构健康 Agent",
  "agent-electrical-diagnosis": "电气诊断 Agent",
  "agent-failure-diagnosis": "故障诊断 Agent",
  "agent-predictive-maintenance": "预测性维护 Agent",
  "agent-meteorological-risk": "气象风险 Agent",
  "agent-maintenance-strategy": "维护策略 Agent",
  "agent-safety-review": "安全审核 Agent",
  "agent-engineering-review": "工程审核 Agent",
  "agent-economic-review": "经济性审核 Agent",
  "agent-compliance": "合规审核 Agent",
  "agent-resource-review": "资源审核 Agent",
  "agent-work-order": "工单 Agent",
  "agent-crew-scheduling": "班组排程 Agent",
  "agent-spare-parts": "备件 Agent",
  "agent-vessel-scheduling": "船舶排程 Agent",
  "agent-maintenance-execution": "维护执行 Agent",
  "agent-scada-control": "SCADA 控制 Agent",
  "agent-report": "报告 Agent",
  "agent-knowledge": "知识 Agent",
};

const skillLabels: Readonly<Record<string, string>> = {
  "mission orchestration": "Mission 编排",
  "priority routing": "优先级路由",
  "conflict resolution": "冲突消解",
  "time-series analysis": "时序分析",
  "signal correlation": "信号关联",
  "data quality": "数据质量",
  FFT: "FFT 快速傅里叶变换",
  "envelope spectrum": "包络谱",
  "order tracking": "阶次跟踪",
  "bearing diagnosis": "轴承诊断",
  "modal analysis": "模态分析",
  "fatigue assessment": "疲劳评估",
  "structural anomaly diagnosis": "结构异常诊断",
  "electrical fault isolation": "电气故障隔离",
  "protection-event analysis": "保护事件分析",
  "power-quality analysis": "电能质量分析",
  "evidence fusion": "证据融合",
  "fault isolation": "故障隔离",
  "confidence calibration": "置信度校准",
  "survival analysis": "生存分析",
  "RUL estimation": "剩余寿命估算",
  "health scoring": "健康评分",
  "marine forecast": "海况预报",
  "weather-window scoring": "天气窗口评分",
  "risk nowcasting": "风险临近预报",
  "maintenance planning": "维护规划",
  "risk-cost optimization": "风险成本优化",
  "energy-loss modeling": "发电损失建模",
  "permit to work": "作业许可",
  LOTO: "上锁挂牌（LOTO）",
  "marine safety": "海上安全",
  "risk assessment": "风险评估",
  "design review": "设计审核",
  "OEM compliance": "厂家要求合规",
  "failure-mode verification": "失效模式验证",
  "energy-yield modeling": "发电量建模",
  "cost estimation": "成本估算",
  "scenario comparison": "方案比较",
  "regulatory mapping": "法规映射",
  "permit compliance": "许可合规",
  "audit-trail review": "审计轨迹审核",
  "resource matching": "资源匹配",
  "inventory validation": "库存校验",
  "schedule feasibility": "排程可行性",
  "work-package generation": "作业包生成",
  "task sequencing": "任务排序",
  "CMMS synchronization": "CMMS 同步",
  "crew rostering": "班组排班",
  "certification matching": "资质匹配",
  "shift planning": "班次规划",
  "inventory allocation": "库存分配",
  "part substitution": "替代料匹配",
  "material reservation": "物料预留",
  "vessel allocation": "船舶分配",
  "route planning": "航线规划",
  "marine constraint checking": "海况约束检查",
  "field-task orchestration": "现场任务编排",
  "execution verification": "执行验证",
  "exception escalation": "异常升级",
  "control interlock verification": "控制联锁校验",
  "state reconciliation": "状态核对",
  "operating-limit checks": "运行边界检查",
  "evidence synthesis": "证据汇总",
  "operations reporting": "运营报告",
  "citation traceability": "引用可追溯性",
  "hybrid retrieval": "混合检索",
  "source citation": "来源引用",
  "case normalization": "案例规范化",
};

export const agentDisplayName = (agentId: string, fallback: string): string =>
  agentNames[agentId] ?? fallback;

export const agentSkillLabel = (skill: string): string => skillLabels[skill] ?? skill;
