import type { Agent, AgentLayer, AgentMetrics, AgentStatus } from "./types";

interface AgentDefinition {
  readonly id: string;
  readonly name: string;
  readonly shortName: string;
  readonly layer: AgentLayer;
  readonly role: string;
  readonly description: string;
  readonly status: AgentStatus;
  readonly currentTask: string | null;
  readonly currentMissionId: string | null;
  readonly queueDepth: number;
  readonly skills: readonly string[];
  readonly tools: readonly string[];
  readonly knowledgeSourceIds: readonly string[];
  readonly metrics: AgentMetrics;
  readonly model?: string;
  readonly promptVersion?: string;
  readonly lastActiveAt?: string;
}

const makeAgent = (definition: AgentDefinition): Agent => ({
  ...definition,
  model:
    definition.model ??
    (definition.layer === "review"
      ? "WindOps-Review-14B"
      : definition.layer === "execution"
        ? "WindOps-Executor-14B"
        : "WindOps-Reasoner-32B"),
  promptVersion: definition.promptVersion ?? "2026.08.3",
  lastActiveAt: definition.lastActiveAt ?? "2026-08-13T10:29:42+08:00",
});

/**
 * Specialist agents arranged into decision, review, and execution layers.
 * Their current assignments intentionally intersect the mission data.
 */
export const agents: readonly Agent[] = [
  makeAgent({
    id: "agent-operations-coordinator",
    name: "Operations Coordinator Agent",
    shortName: "Operations Coordinator",
    layer: "decision",
    role: "任务编排与跨专业协调",
    description: "拆解异常事件、选择专业 Agent，并维护诊断到执行的闭环。",
    status: "working",
    currentTask: "协调 WT-023 作业窗口与资源确认",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["mission orchestration", "priority routing", "conflict resolution"],
    tools: ["query_alarm_history", "get_turbine_status", "create_decision"],
    knowledgeSourceIds: ["KB-OPS-PROC-002", "KB-SAFETY-STD-011"],
    metrics: {
      successRate: 97.8,
      averageLatencySeconds: 4.8,
      requests24h: 186,
      toolCalls24h: 522,
      tokenUsage24h: 184320,
      missionsCompleted: 428,
    },
  }),
  makeAgent({
    id: "agent-scada-analysis",
    name: "SCADA Analysis Agent",
    shortName: "SCADA Analysis",
    layer: "decision",
    role: "实时测点分析与异常检出",
    description: "关联功率、温度、转速和控制信号，识别持续偏离与数据质量问题。",
    status: "working",
    currentTask: "监测 WT-023 降载前基线",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 4,
    skills: ["time-series analysis", "signal correlation", "data quality"],
    tools: ["query_scada", "get_turbine_status", "calculate_health_score"],
    knowledgeSourceIds: ["KB-SCADA-REPORT-023", "KB-GW165-OM-001"],
    metrics: {
      successRate: 98.2,
      averageLatencySeconds: 3.7,
      requests24h: 1248,
      toolCalls24h: 2864,
      tokenUsage24h: 218440,
      missionsCompleted: 611,
    },
  }),
  makeAgent({
    id: "agent-vibration-diagnosis",
    name: "Vibration Diagnosis Agent",
    shortName: "Vibration Diagnosis",
    layer: "decision",
    role: "传动链振动频谱诊断",
    description: "分析 RMS、包络谱和阶次特征，区分不平衡、松动与轴承退化。",
    status: "working",
    currentTask: "WT-023 主轴承诊断",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 3,
    skills: ["FFT", "envelope spectrum", "order tracking", "bearing diagnosis"],
    tools: ["query_vibration", "query_scada", "query_similar_failures"],
    knowledgeSourceIds: ["KB-MB-PROC-004", "KB-CASE-2019-017", "KB-ISO-10816"],
    metrics: {
      successRate: 94.6,
      averageLatencySeconds: 12.3,
      requests24h: 94,
      toolCalls24h: 318,
      tokenUsage24h: 156780,
      missionsCompleted: 286,
    },
  }),
  makeAgent({
    id: "agent-structural-health",
    name: "Structural Health Agent",
    shortName: "Structural Health",
    layer: "decision",
    role: "塔筒、基础与叶片结构健康诊断",
    description: "关联固有频率、载荷和历史缺陷，评估结构退化与现场复核优先级。",
    status: "thinking",
    currentTask: "复核 WT-018 塔筒一阶频率偏移",
    currentMissionId: "MISSION-2026-0821",
    queueDepth: 2,
    skills: ["modal analysis", "fatigue assessment", "structural anomaly diagnosis"],
    tools: ["query_scada", "query_similar_failures", "query_manual", "calculate_health_score"],
    knowledgeSourceIds: ["KB-GW165-OM-001", "KB-ISO-10816", "KB-SAFETY-STD-011"],
    metrics: {
      successRate: 95.4,
      averageLatencySeconds: 16.8,
      requests24h: 61,
      toolCalls24h: 214,
      tokenUsage24h: 148260,
      missionsCompleted: 173,
    },
  }),
  makeAgent({
    id: "agent-electrical-diagnosis",
    name: "Electrical Diagnosis Agent",
    shortName: "Electrical Diagnosis",
    layer: "decision",
    role: "变流器、发电机与电网侧故障诊断",
    description: "关联电压、电流、温度和保护事件，区分机组电气故障与场站电网扰动。",
    status: "working",
    currentTask: "关联 WT-045 电压跌落与保护事件序列",
    currentMissionId: "MISSION-2026-0828",
    queueDepth: 3,
    skills: ["electrical fault isolation", "protection-event analysis", "power-quality analysis"],
    tools: ["query_scada", "query_alarm_history", "query_manual", "query_similar_failures"],
    knowledgeSourceIds: ["KB-GW165-OM-001", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 96.3,
      averageLatencySeconds: 11.9,
      requests24h: 88,
      toolCalls24h: 273,
      tokenUsage24h: 163910,
      missionsCompleted: 219,
    },
  }),
  makeAgent({
    id: "agent-failure-diagnosis",
    name: "Failure Diagnosis Agent",
    shortName: "Failure Diagnosis",
    layer: "decision",
    role: "多源证据融合与故障判定",
    description: "融合信号、维护记录和故障案例，输出可审计诊断及置信度。",
    status: "thinking",
    currentTask: "融合 WT-023 主轴承多源证据并复核诊断边界",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["evidence fusion", "fault isolation", "confidence calibration"],
    tools: ["query_alarm_history", "query_similar_failures", "query_maintenance_history"],
    knowledgeSourceIds: ["KB-CASE-2019-017", "KB-GEARBOX-CASE-022"],
    metrics: {
      successRate: 95.8,
      averageLatencySeconds: 18.6,
      requests24h: 73,
      toolCalls24h: 291,
      tokenUsage24h: 211540,
      missionsCompleted: 244,
    },
  }),
  makeAgent({
    id: "agent-predictive-maintenance",
    name: "Predictive Maintenance Agent",
    shortName: "Predictive Maintenance",
    layer: "decision",
    role: "健康评分、失效概率与 RUL 预测",
    description: "运行健康退化模型并给出未来 30 天风险和剩余寿命区间。",
    status: "working",
    currentTask: "更新 WT-023 主轴承 RUL",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 5,
    skills: ["survival analysis", "RUL estimation", "health scoring"],
    tools: ["predict_rul", "calculate_health_score", "query_maintenance_history"],
    knowledgeSourceIds: ["KB-MB-PROC-004", "KB-SCADA-REPORT-023"],
    metrics: {
      successRate: 93.9,
      averageLatencySeconds: 21.4,
      requests24h: 132,
      toolCalls24h: 402,
      tokenUsage24h: 194630,
      missionsCompleted: 198,
    },
  }),
  makeAgent({
    id: "agent-meteorological-risk",
    name: "Meteorological Risk Agent",
    shortName: "Meteorological Risk",
    layer: "decision",
    role: "海况预测与作业窗口评估",
    description: "评估风速、阵风、浪高、能见度与雷电对海上作业的约束。",
    status: "working",
    currentTask: "确认 8 月 14 日 WT-023 登塔窗口",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 1,
    skills: ["marine forecast", "weather-window scoring", "risk nowcasting"],
    tools: ["query_weather", "get_turbine_status"],
    knowledgeSourceIds: ["KB-SAFETY-STD-011", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 96.7,
      averageLatencySeconds: 5.9,
      requests24h: 206,
      toolCalls24h: 391,
      tokenUsage24h: 103840,
      missionsCompleted: 317,
    },
  }),
  makeAgent({
    id: "agent-maintenance-strategy",
    name: "Maintenance Strategy Agent",
    shortName: "Maintenance Strategy",
    layer: "decision",
    role: "维护方案与成本风险权衡",
    description: "比较停机、降载和增强监测策略，形成可执行的推荐方案。",
    status: "waiting",
    currentTask: "等待 WT-023 现场检查结果",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["maintenance planning", "risk-cost optimization", "energy-loss modeling"],
    tools: ["create_decision", "query_weather", "query_work_orders"],
    knowledgeSourceIds: ["KB-MB-PROC-004", "KB-WO-2025-118"],
    metrics: {
      successRate: 96.1,
      averageLatencySeconds: 15.2,
      requests24h: 68,
      toolCalls24h: 236,
      tokenUsage24h: 147920,
      missionsCompleted: 231,
    },
  }),
  makeAgent({
    id: "agent-safety-review",
    name: "Safety Review Agent",
    shortName: "Safety Review",
    layer: "review",
    role: "作业安全与控制措施审核",
    description: "核查 PPE、隔离程序、海况限制和高风险动作的人工审批要求。",
    status: "reviewing",
    currentTask: "审核 WT-023 主轴承检查方案与高风险控制措施",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["permit to work", "LOTO", "marine safety", "risk assessment"],
    tools: ["query_manual", "query_weather", "query_work_orders"],
    knowledgeSourceIds: ["KB-SAFETY-STD-011", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 99.1,
      averageLatencySeconds: 8.1,
      requests24h: 91,
      toolCalls24h: 248,
      tokenUsage24h: 112300,
      missionsCompleted: 394,
    },
  }),
  makeAgent({
    id: "agent-engineering-review",
    name: "Engineering Review Agent",
    shortName: "Engineering Review",
    layer: "review",
    role: "技术可行性与方案边界审核",
    description: "校核诊断依据、载荷边界、厂家要求和检修方法的可行性。",
    status: "idle",
    currentTask: null,
    currentMissionId: null,
    queueDepth: 1,
    skills: ["design review", "OEM compliance", "failure-mode verification"],
    tools: ["query_manual", "query_scada", "query_similar_failures"],
    knowledgeSourceIds: ["KB-GW165-OM-001", "KB-MB-PROC-004"],
    metrics: {
      successRate: 98.4,
      averageLatencySeconds: 10.7,
      requests24h: 64,
      toolCalls24h: 193,
      tokenUsage24h: 120560,
      missionsCompleted: 326,
    },
  }),
  makeAgent({
    id: "agent-economic-review",
    name: "Economic Review Agent",
    shortName: "Economic Review",
    layer: "review",
    role: "发电损失与全生命周期成本审核",
    description: "比较停机损失、维修成本、故障恶化风险和资源机会成本。",
    status: "reviewing",
    currentTask: "比较 WT-041 三项维护方案",
    currentMissionId: "MISSION-2026-0824",
    queueDepth: 2,
    skills: ["energy-yield modeling", "cost estimation", "scenario comparison"],
    tools: ["query_scada", "query_work_orders", "create_decision"],
    knowledgeSourceIds: ["KB-WO-2025-118", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 97.2,
      averageLatencySeconds: 7.6,
      requests24h: 58,
      toolCalls24h: 176,
      tokenUsage24h: 98420,
      missionsCompleted: 278,
    },
  }),
  makeAgent({
    id: "agent-compliance",
    name: "Compliance Agent",
    shortName: "Compliance",
    layer: "review",
    role: "法规、标准与作业许可合规审核",
    description: "核对维护方案、作业许可、记录留痕和标准条款，标记需要人工确认的合规门槛。",
    status: "reviewing",
    currentTask: "核对 WT-023 作业包许可与留痕要求",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["regulatory mapping", "permit compliance", "audit-trail review"],
    tools: ["query_manual", "query_work_orders", "query_weather"],
    knowledgeSourceIds: ["KB-SAFETY-STD-011", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 99.3,
      averageLatencySeconds: 8.9,
      requests24h: 49,
      toolCalls24h: 139,
      tokenUsage24h: 82640,
      missionsCompleted: 301,
    },
  }),
  makeAgent({
    id: "agent-resource-review",
    name: "Resource Review Agent",
    shortName: "Resource Review",
    layer: "review",
    role: "人员、船舶、备件与工具校核",
    description: "验证计划窗口内的班组资质、船舶、备件库存和专用工具可用性。",
    status: "working",
    currentTask: "锁定 WT-023 轴承检查资源",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 3,
    skills: ["resource matching", "inventory validation", "schedule feasibility"],
    tools: ["query_spare_parts", "query_crew", "query_vessels", "query_weather"],
    knowledgeSourceIds: ["KB-MB-PROC-004", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 97.6,
      averageLatencySeconds: 6.4,
      requests24h: 116,
      toolCalls24h: 423,
      tokenUsage24h: 88960,
      missionsCompleted: 342,
    },
  }),
  makeAgent({
    id: "agent-work-order",
    name: "Work Order Agent",
    shortName: "Work Order",
    layer: "execution",
    role: "结构化工单生成与状态同步",
    description: "把批准的维护决策转换为任务、物料、安全措施和计划时间。",
    status: "working",
    currentTask: "完善 WO-20260823-017 作业包",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["work-package generation", "task sequencing", "CMMS synchronization"],
    tools: ["create_work_order", "query_manual", "query_spare_parts"],
    knowledgeSourceIds: ["KB-MB-PROC-004", "KB-SAFETY-STD-011"],
    metrics: {
      successRate: 98.8,
      averageLatencySeconds: 4.2,
      requests24h: 83,
      toolCalls24h: 304,
      tokenUsage24h: 91340,
      missionsCompleted: 486,
    },
  }),
  makeAgent({
    id: "agent-crew-scheduling",
    name: "Crew Scheduling Agent",
    shortName: "Crew Scheduling",
    layer: "execution",
    role: "班组资质匹配与排班",
    description: "按技能、工时和海上作业资质分配维护班组。",
    status: "working",
    currentTask: "安排海维二组 8 月 14 日出海",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 1,
    skills: ["crew rostering", "certification matching", "shift planning"],
    tools: ["query_crew", "query_weather", "update_work_order"],
    knowledgeSourceIds: ["KB-OPS-PROC-002"],
    metrics: {
      successRate: 98.1,
      averageLatencySeconds: 3.8,
      requests24h: 102,
      toolCalls24h: 237,
      tokenUsage24h: 58620,
      missionsCompleted: 509,
    },
  }),
  makeAgent({
    id: "agent-spare-parts",
    name: "Spare Parts Agent",
    shortName: "Spare Parts",
    layer: "execution",
    role: "备件库存、预留与工单物料协调",
    description: "核对可用量、预留关系与替代料，把备件约束同步到维护工单草案。",
    status: "working",
    currentTask: "确认 WT-023 检查包耗材与替代料库存",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["inventory allocation", "part substitution", "material reservation"],
    tools: ["query_spare_parts", "query_work_orders", "update_work_order"],
    knowledgeSourceIds: ["KB-MB-PROC-004", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 98.6,
      averageLatencySeconds: 3.4,
      requests24h: 121,
      toolCalls24h: 286,
      tokenUsage24h: 61380,
      missionsCompleted: 447,
    },
  }),
  makeAgent({
    id: "agent-vessel-scheduling",
    name: "Vessel Scheduling Agent",
    shortName: "Vessel Scheduling",
    layer: "execution",
    role: "运维船舶与航次计划",
    description: "结合海况、航程和载荷能力预留 CTV 或大型作业船。",
    status: "waiting",
    currentTask: "等待 CTV-03 船长最终确认",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 1,
    skills: ["vessel allocation", "route planning", "marine constraint checking"],
    tools: ["query_vessels", "query_weather", "update_work_order"],
    knowledgeSourceIds: ["KB-OPS-PROC-002", "KB-SAFETY-STD-011"],
    metrics: {
      successRate: 97.9,
      averageLatencySeconds: 4.6,
      requests24h: 76,
      toolCalls24h: 184,
      tokenUsage24h: 52110,
      missionsCompleted: 413,
    },
  }),
  makeAgent({
    id: "agent-maintenance-execution",
    name: "Maintenance Execution Agent",
    shortName: "Maintenance Execution",
    layer: "execution",
    role: "现场任务编排、进度核验与异常升级",
    description: "依据已批准工单跟踪现场步骤、资产状态和执行记录，并把偏差升级给人工负责人。",
    status: "waiting",
    currentTask: "等待 WT-023 作业许可后启动现场任务",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 1,
    skills: ["field-task orchestration", "execution verification", "exception escalation"],
    tools: ["query_work_orders", "query_manual", "get_turbine_status", "update_work_order"],
    knowledgeSourceIds: ["KB-MB-PROC-004", "KB-SAFETY-STD-011", "KB-OPS-PROC-002"],
    metrics: {
      successRate: 98.9,
      averageLatencySeconds: 4.9,
      requests24h: 79,
      toolCalls24h: 226,
      tokenUsage24h: 74210,
      missionsCompleted: 368,
    },
  }),
  makeAgent({
    id: "agent-scada-control",
    name: "SCADA Control Agent",
    shortName: "SCADA Control",
    layer: "execution",
    role: "控制动作前置校验与状态回读",
    description: "读取机组状态、告警和测点，校验人工控制动作的前置条件并持续核对执行结果。",
    status: "waiting",
    currentTask: "校验 WT-023 降载动作前置状态",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 1,
    skills: ["control interlock verification", "state reconciliation", "operating-limit checks"],
    tools: ["get_turbine_status", "query_scada", "query_alarm_history"],
    knowledgeSourceIds: ["KB-GW165-OM-001", "KB-SCADA-REPORT-023", "KB-SAFETY-STD-011"],
    metrics: {
      successRate: 99.4,
      averageLatencySeconds: 2.7,
      requests24h: 214,
      toolCalls24h: 462,
      tokenUsage24h: 66950,
      missionsCompleted: 532,
    },
  }),
  makeAgent({
    id: "agent-report",
    name: "Report Agent",
    shortName: "Report",
    layer: "execution",
    role: "可追溯运维报告生成与闭环摘要",
    description: "汇总 SCADA、告警、工单和知识引用，生成带来源边界的运维报告草案。",
    status: "working",
    currentTask: "生成 WT-041 齿轮箱诊断阶段报告",
    currentMissionId: "MISSION-2026-0824",
    queueDepth: 3,
    skills: ["evidence synthesis", "operations reporting", "citation traceability"],
    tools: ["query_scada", "query_alarm_history", "query_work_orders", "query_manual"],
    knowledgeSourceIds: ["KB-GEARBOX-CASE-022", "KB-OPS-PROC-002", "KB-GW165-OM-001"],
    metrics: {
      successRate: 97.5,
      averageLatencySeconds: 6.7,
      requests24h: 97,
      toolCalls24h: 318,
      tokenUsage24h: 128760,
      missionsCompleted: 406,
    },
  }),
  makeAgent({
    id: "agent-knowledge",
    name: "Knowledge Agent",
    shortName: "Knowledge",
    layer: "execution",
    role: "RAG 检索、引用与案例沉淀",
    description: "检索可追溯的手册、历史案例和工单，并在闭环后沉淀新知识。",
    status: "waiting",
    currentTask: "等待 WT-023 闭环后沉淀可追溯案例",
    currentMissionId: "MISSION-2026-0823",
    queueDepth: 2,
    skills: ["hybrid retrieval", "source citation", "case normalization"],
    tools: ["query_manual", "query_similar_failures", "query_maintenance_history"],
    knowledgeSourceIds: ["KB-GW165-OM-001", "KB-CASE-2019-017", "KB-WO-2025-118"],
    metrics: {
      successRate: 96.9,
      averageLatencySeconds: 2.9,
      requests24h: 344,
      toolCalls24h: 916,
      tokenUsage24h: 264700,
      missionsCompleted: 557,
    },
  }),
] as const;

export const agentLayers = {
  decision: agents.filter((agent) => agent.layer === "decision"),
  review: agents.filter((agent) => agent.layer === "review"),
  execution: agents.filter((agent) => agent.layer === "execution"),
} as const;
