import type { KnowledgeDocument } from "./types";

/**
 * Search-ready knowledge sources. IDs are referenced by agents and evidence so
 * a RAG preview can render real citations rather than invented source labels.
 */
export const knowledgeDocuments: readonly KnowledgeDocument[] = [
  {
    id: "KB-GW165-OM-001",
    title: "GW165-6.0MW 运行维护手册",
    type: "equipment-manual",
    equipment: "整机 / 传动链",
    manufacturer: "Goldwind",
    version: "Rev. 6.2",
    updatedAt: "2026-05-18T14:20:00+08:00",
    vectorized: true,
    pageCount: 486,
    language: "zh-CN",
    tags: ["GW165", "运行限值", "主轴承", "故障代码"],
    summary: "包含整机运行边界、告警处理、传动链检查和计划维护要求。",
    relatedTurbineIds: ["WT-023", "WT-041"],
    relatedMissionIds: ["MISSION-2026-0823", "MISSION-2026-0824"],
  },
  {
    id: "KB-MB-PROC-004",
    title: "海上风机主轴承状态检查与取证规程",
    type: "maintenance-procedure",
    equipment: "主轴承",
    manufacturer: null,
    version: "OPS-MB-04.3",
    updatedAt: "2026-07-02T09:10:00+08:00",
    vectorized: true,
    pageCount: 42,
    language: "zh-CN",
    tags: ["主轴承", "振动", "润滑", "内窥镜", "取证"],
    summary: "规定振动复测、温度核验、润滑脂取样和内窥镜检查步骤及判据。",
    relatedTurbineIds: ["WT-023"],
    relatedMissionIds: ["MISSION-2026-0823"],
  },
  {
    id: "KB-CASE-2019-017",
    title: "主轴承早期剥落：振动与温升联合案例",
    type: "failure-case",
    equipment: "主轴承",
    manufacturer: "Goldwind",
    version: "Case 2019-017 / Reviewed",
    updatedAt: "2026-04-26T16:45:00+08:00",
    vectorized: true,
    pageCount: 18,
    language: "zh-CN",
    tags: ["早期剥落", "包络谱", "温升", "相似案例"],
    summary: "历史机组在振动 RMS 增长 24% 且温升 7.9°C 后发现滚道早期剥落。",
    relatedTurbineIds: ["WT-023"],
    relatedMissionIds: ["MISSION-2026-0823"],
  },
  {
    id: "KB-SCADA-REPORT-023",
    title: "WT-023 近 90 天 SCADA 与振动趋势联合分析",
    type: "scada-analysis-report",
    equipment: "WT-023 / 主轴承",
    manufacturer: null,
    version: "2026-08-13.1",
    updatedAt: "2026-08-13T02:14:28+08:00",
    vectorized: true,
    pageCount: 31,
    language: "zh-CN",
    tags: ["WT-023", "SCADA", "振动 RMS", "Anomaly 0.86"],
    summary: "记录主轴承振动增长 27%、温升 8.4°C 与功率波动增长 6% 的关联趋势。",
    relatedTurbineIds: ["WT-023"],
    relatedMissionIds: ["MISSION-2026-0823"],
  },
  {
    id: "KB-ISO-10816",
    title: "ISO 10816 风力发电机组振动评价摘录",
    type: "technical-standard",
    equipment: "旋转机械",
    manufacturer: null,
    version: "ISO 10816-21:2015",
    updatedAt: "2025-12-12T11:30:00+08:00",
    vectorized: true,
    pageCount: 36,
    language: "en-US",
    tags: ["ISO 10816", "振动阈值", "RMS", "旋转机械"],
    summary: "提供风力发电机组部件振动测量与评价区域的参考边界。",
    relatedTurbineIds: ["WT-023"],
    relatedMissionIds: ["MISSION-2026-0823"],
  },
  {
    id: "KB-WO-2025-118",
    title: "WO-20250718-118 主轴承润滑异常处理记录",
    type: "historical-work-order",
    equipment: "主轴承润滑系统",
    manufacturer: "Goldwind",
    version: "Closed / Rev. 2",
    updatedAt: "2025-07-22T17:05:00+08:00",
    vectorized: true,
    pageCount: 24,
    language: "zh-CN",
    tags: ["历史工单", "润滑脂", "振动复测", "停机 6h"],
    summary: "相似机组通过补脂、排脂检查和复测排除了润滑不足，并恢复健康评分。",
    relatedTurbineIds: ["WT-023"],
    relatedMissionIds: ["MISSION-2026-0823"],
  },
  {
    id: "KB-SAFETY-STD-011",
    title: "海上风机登塔与机舱作业安全标准",
    type: "technical-standard",
    equipment: "海上作业",
    manufacturer: null,
    version: "HSE-OW-11.7",
    updatedAt: "2026-06-14T08:40:00+08:00",
    vectorized: true,
    pageCount: 68,
    language: "zh-CN",
    tags: ["PPE", "LOTO", "人员转运", "风浪限制"],
    summary: "定义 CTV 转运、登塔、机舱作业、能源隔离和应急撤离控制措施。",
    relatedTurbineIds: ["WT-018", "WT-023"],
    relatedMissionIds: ["MISSION-2026-0821", "MISSION-2026-0823"],
  },
  {
    id: "KB-OPS-PROC-002",
    title: "海上运维任务策划与资源协调程序",
    type: "maintenance-procedure",
    equipment: "运维资源",
    manufacturer: null,
    version: "OPS-PLAN-02.5",
    updatedAt: "2026-03-30T13:25:00+08:00",
    vectorized: true,
    pageCount: 55,
    language: "zh-CN",
    tags: ["作业窗口", "CTV", "班组", "备件", "审批"],
    summary: "规定维护方案从风险评估、资源确认、人工审批到工单执行的流程。",
    relatedTurbineIds: ["WT-023", "WT-029"],
    relatedMissionIds: ["MISSION-2026-0820", "MISSION-2026-0823"],
  },
  {
    id: "KB-GEARBOX-CASE-022",
    title: "齿轮箱磨粒计数快速上升故障案例",
    type: "failure-case",
    equipment: "齿轮箱",
    manufacturer: "Goldwind",
    version: "Case 2024-022",
    updatedAt: "2026-01-19T10:15:00+08:00",
    vectorized: true,
    pageCount: 21,
    language: "zh-CN",
    tags: ["齿轮箱", "磨粒", "油液", "齿面点蚀"],
    summary: "总结磨粒告警、油样分析与齿面点蚀之间的诊断路径和停机准则。",
    relatedTurbineIds: ["WT-041"],
    relatedMissionIds: ["MISSION-2026-0824"],
  },
  {
    id: "KB-INSPECTION-023-2026Q2",
    title: "WT-023 2026 Q2 定期巡检报告",
    type: "inspection-report",
    equipment: "WT-023 / 传动链",
    manufacturer: null,
    version: "Q2-Final",
    updatedAt: "2026-06-21T15:40:00+08:00",
    vectorized: true,
    pageCount: 29,
    language: "zh-CN",
    tags: ["WT-023", "巡检", "主轴承", "润滑脂"],
    summary: "二季度巡检无可见损伤，但记录驱动端润滑脂颜色轻微变深，建议趋势跟踪。",
    relatedTurbineIds: ["WT-023"],
    relatedMissionIds: ["MISSION-2026-0823"],
  },
] as const;

