import { weatherWindows } from "./telemetry-data";
import type {
  MaintenanceCrew,
  MaintenanceTool,
  ResourceCenterSnapshot,
  ServiceVessel,
  SparePart,
} from "./types";

const FEATURED_WORK_ORDER_ID = "WO-20260823-017";

export const spareParts: readonly SparePart[] = [
  {
    id: "SP-GW165-MAIN-BEARING",
    partNumber: "GB-MB-165-01",
    name: "GW165 主轴承总成",
    category: "传动链",
    warehouse: "东海运维基地 · A-03",
    onHand: 2,
    reserved: 1,
    available: 1,
    reorderPoint: 1,
    unit: "套",
    status: "low-stock",
    reservedForWorkOrderIds: [FEATURED_WORK_ORDER_ID],
    compatibleTurbineModels: ["GW165-6.0MW"],
    updatedAt: "2026-08-13T10:25:00+08:00",
  },
  {
    id: "SP-MAIN-BEARING-GREASE",
    partNumber: "GR-LUBE-460-20",
    name: "主轴承专用润滑脂 20 kg",
    category: "润滑材料",
    warehouse: "东海运维基地 · C-08",
    onHand: 12,
    reserved: 2,
    available: 10,
    reorderPoint: 4,
    unit: "桶",
    status: "in-stock",
    reservedForWorkOrderIds: [FEATURED_WORK_ORDER_ID],
    compatibleTurbineModels: ["GW165-6.0MW", "GW171-6.5MW"],
    updatedAt: "2026-08-13T10:25:00+08:00",
  },
  {
    id: "SP-GEARBOX-FILTER",
    partNumber: "GBX-FILTER-GW165",
    name: "齿轮箱精滤芯",
    category: "传动链",
    warehouse: "东海运维基地 · A-07",
    onHand: 8,
    reserved: 2,
    available: 6,
    reorderPoint: 3,
    unit: "件",
    status: "in-stock",
    reservedForWorkOrderIds: ["WO-20260812-015"],
    compatibleTurbineModels: ["GW165-6.0MW"],
    updatedAt: "2026-08-13T09:40:00+08:00",
  },
  {
    id: "SP-PITCH-BATTERY",
    partNumber: "PITCH-BAT-400-18",
    name: "变桨后备电池组",
    category: "变桨系统",
    warehouse: "东海运维基地 · B-12",
    onHand: 3,
    reserved: 0,
    available: 3,
    reorderPoint: 2,
    unit: "组",
    status: "in-stock",
    reservedForWorkOrderIds: [],
    compatibleTurbineModels: ["GW165-6.0MW"],
    updatedAt: "2026-08-13T08:30:00+08:00",
  },
  {
    id: "SP-CONVERTER-PUMP",
    partNumber: "CNV-PUMP-22K",
    name: "变流器冷却泵",
    category: "电气系统",
    warehouse: "东海运维基地 · B-04",
    onHand: 2,
    reserved: 1,
    available: 1,
    reorderPoint: 2,
    unit: "台",
    status: "low-stock",
    reservedForWorkOrderIds: ["WO-20260813-016"],
    compatibleTurbineModels: ["GW165-6.0MW"],
    updatedAt: "2026-08-13T09:55:00+08:00",
  },
  {
    id: "SP-YAW-BRAKE-PAD",
    partNumber: "YAW-PAD-165-A",
    name: "偏航制动器摩擦片",
    category: "偏航系统",
    warehouse: "东海运维基地 · A-11",
    onHand: 16,
    reserved: 0,
    available: 16,
    reorderPoint: 8,
    unit: "片",
    status: "in-stock",
    reservedForWorkOrderIds: [],
    compatibleTurbineModels: ["GW165-6.0MW", "GW171-6.5MW"],
    updatedAt: "2026-08-12T16:20:00+08:00",
  },
  {
    id: "SP-BLADE-LE-TAPE",
    partNumber: "BLD-LE-TAPE-300",
    name: "叶片前缘保护带",
    category: "叶片",
    warehouse: "东海运维基地 · D-02",
    onHand: 0,
    reserved: 0,
    available: 0,
    reorderPoint: 4,
    unit: "卷",
    status: "out-of-stock",
    reservedForWorkOrderIds: [],
    compatibleTurbineModels: ["GW165-6.0MW"],
    updatedAt: "2026-08-13T07:50:00+08:00",
  },
] as const;

export const maintenanceCrews: readonly MaintenanceCrew[] = [
  {
    id: "CREW-OFFSHORE-02",
    name: "海维二组",
    specialties: ["传动链", "主轴承", "状态监测"],
    memberCount: 4,
    availability: "reserved",
    assignedWorkOrderId: FEATURED_WORK_ORDER_ID,
    certifications: ["海上作业 GWO", "高处作业", "机械 LOTO"],
    currentLocation: "东海运维基地",
  },
  {
    id: "CREW-ELECTRICAL-01",
    name: "高压电气一组",
    specialties: ["变流器", "箱变", "继电保护"],
    memberCount: 5,
    availability: "assigned",
    assignedWorkOrderId: "WO-20260811-012",
    certifications: ["高压电工作业", "海上作业 GWO"],
    currentLocation: "WT-029",
  },
  {
    id: "CREW-BLADE-03",
    name: "叶片检修三组",
    specialties: ["绳索作业", "叶片修复", "无人机复核"],
    memberCount: 3,
    availability: "available",
    assignedWorkOrderId: null,
    certifications: ["IRATA L2", "复合材料修复"],
    currentLocation: "东海运维基地",
  },
  {
    id: "CREW-STRUCTURE-01",
    name: "结构专业组",
    specialties: ["塔筒", "基础", "螺栓预紧力"],
    memberCount: 4,
    availability: "reserved",
    assignedWorkOrderId: "WO-20260812-014",
    certifications: ["超声检测 UT2", "液压工具操作"],
    currentLocation: "东海运维基地",
  },
] as const;

export const serviceVessels: readonly ServiceVessel[] = [
  {
    id: "VESSEL-CTV-03",
    name: "CTV-03 东海迅捷",
    vesselType: "CTV",
    availability: "reserved",
    assignedWorkOrderId: FEATURED_WORK_ORDER_ID,
    capacity: 12,
    maxWaveHeightM: 1.8,
    berth: "2 号泊位",
    eta: "2026-08-14T07:20:00+08:00",
  },
  {
    id: "VESSEL-CTV-01",
    name: "CTV-01 蓝鲸",
    vesselType: "CTV",
    availability: "available",
    assignedWorkOrderId: null,
    capacity: 12,
    maxWaveHeightM: 1.7,
    berth: "1 号泊位",
    eta: null,
  },
  {
    id: "VESSEL-SOV-02",
    name: "SOV-02 海工协同",
    vesselType: "SOV",
    availability: "assigned",
    assignedWorkOrderId: "WO-20260812-015",
    capacity: 60,
    maxWaveHeightM: 2.5,
    berth: "海上驻留",
    eta: "2026-08-14T06:40:00+08:00",
  },
] as const;

export const maintenanceTools: readonly MaintenanceTool[] = [
  {
    id: "TOOL-CMS-PORTABLE-04",
    name: "便携式振动分析仪 CMS-04",
    category: "状态监测",
    availability: "reserved",
    assignedWorkOrderId: FEATURED_WORK_ORDER_ID,
    calibrationDueAt: "2027-01-18T00:00:00+08:00",
    location: "海维二组工具柜",
  },
  {
    id: "TOOL-BORESCOPE-02",
    name: "工业内窥镜 BS-02",
    category: "机械检查",
    availability: "reserved",
    assignedWorkOrderId: FEATURED_WORK_ORDER_ID,
    calibrationDueAt: "2026-11-02T00:00:00+08:00",
    location: "A 区仪器室",
  },
  {
    id: "TOOL-IR-CAMERA-05",
    name: "红外热像仪 IR-05",
    category: "热成像",
    availability: "reserved",
    assignedWorkOrderId: FEATURED_WORK_ORDER_ID,
    calibrationDueAt: "2027-02-12T00:00:00+08:00",
    location: "海维二组工具柜",
  },
  {
    id: "TOOL-GREASE-SAMPLER-08",
    name: "润滑脂取样套件 GS-08",
    category: "润滑分析",
    availability: "reserved",
    assignedWorkOrderId: FEATURED_WORK_ORDER_ID,
    calibrationDueAt: "2027-04-30T00:00:00+08:00",
    location: "C 区耗材室",
  },
  {
    id: "TOOL-HYD-TORQUE-03",
    name: "液压扭矩工具 HT-03",
    category: "结构检查",
    availability: "assigned",
    assignedWorkOrderId: "WO-20260812-014",
    calibrationDueAt: "2026-10-18T00:00:00+08:00",
    location: "结构专业组",
  },
  {
    id: "TOOL-UAV-07",
    name: "工业巡检无人机 UAV-07",
    category: "空中检查",
    availability: "available",
    assignedWorkOrderId: null,
    calibrationDueAt: "2027-03-01T00:00:00+08:00",
    location: "飞行器库",
  },
] as const;

export const resourceCenterSnapshot: ResourceCenterSnapshot = Object.freeze({
  spareParts,
  crews: maintenanceCrews,
  vessels: serviceVessels,
  tools: maintenanceTools,
  weatherWindows,
  snapshotAt: "2026-08-13T10:25:00+08:00",
});

export function getResourcesForWorkOrder(workOrderId: string) {
  const normalized = workOrderId.trim().toUpperCase();
  return Object.freeze({
    spareParts: spareParts.filter((item) => item.reservedForWorkOrderIds.includes(normalized)),
    crews: maintenanceCrews.filter((item) => item.assignedWorkOrderId === normalized),
    vessels: serviceVessels.filter((item) => item.assignedWorkOrderId === normalized),
    tools: maintenanceTools.filter((item) => item.assignedWorkOrderId === normalized),
    weatherWindows: normalized === FEATURED_WORK_ORDER_ID ? weatherWindows : [],
  });
}
