"use client";

import { useState } from "react";
import { Activity, TriangleAlert as AlarmTriangle, ArrowRight, Bot, Check, CheckCircle2, ChevronRight, FileSearch, GitBranch, Link2, MessageSquareText, MoreHorizontal, RefreshCcw, ShieldCheck, Sparkles, TerminalSquare, UserCheck, CloudSun as WeatherSun, Wrench, X } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/layout/page-header";
import { Avatar, Button, Card, CardHeader, KeyValue, Progress } from "@/components/ui/primitives";
import { StatusBadge } from "@/components/data-display/status-badge";
import { activityEvents, agents, evidenceItems, featuredDecision, featuredMission, turbine023, weatherWindows, workOrders } from "@/lib";
import type { ActivityEvent } from "@/lib/types";
import { cn } from "@/lib/utils";

const steps = ["Detected", "Investigating", "Diagnosed", "Decision", "Review", "Approved", "Executing", "Completed"];
const activityIcon: Record<ActivityEvent["kind"], typeof Activity> = { detection: AlarmTriangle, analysis: Activity, retrieval: FileSearch, diagnosis: Sparkles, decision: GitBranch, review: ShieldCheck, approval: UserCheck, "work-order": Wrench, execution: TerminalSquare, system: Bot };

function formatTime(timestamp: string) {
  return new Date(timestamp).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false });
}

export function MissionDetailPage() {
  const [approval, setApproval] = useState<"pending" | "approved" | "rejected" | "revision">("approved");
  const relatedEvents = activityEvents.filter((event) => event.missionId === featuredMission.id);
  const relatedEvidence = evidenceItems.filter((item) => item.missionId === featuredMission.id);
  const missionAgents = agents.filter((agent) => featuredMission.agentIds.includes(agent.id));
  const recommended = featuredDecision.alternatives.find((item) => item.id === featuredDecision.recommendedAlternativeId) ?? featuredDecision.alternatives[0];
  const window = weatherWindows.find((item) => item.id === featuredDecision.weatherWindowId) ?? weatherWindows[0];
  const workOrder = workOrders.find((item) => item.id === featuredMission.workOrderId);
  const progress = approval === "pending" ? 67 : featuredMission.progressPercent;

  return <AppShell activePath="/missions/MISSION-2026-0823">
    <PageHeader eyebrow="MISSION DETAIL" title={featuredMission.id} description={`${turbine023.id} · ${featuredMission.title} · 多 Agent 协同诊断与运维决策`} breadcrumb={["AI Operations", "Mission Center", featuredMission.id]} meta={<><StatusBadge value={approval === "pending" ? "under-review" : featuredMission.status} label={approval === "pending" ? "APPROVAL REPLAY" : "EXECUTING"} tone={approval === "pending" ? "warning" : "info"} pulse /><StatusBadge value={featuredMission.severity} label="HIGH SEVERITY" tone="critical" /><span className="page-meta-text">创建于 02:14 · 更新于 2 分钟前</span></>} actions={<><Button variant="secondary"><TerminalSquare size={15} /> Export Log</Button><Button variant="secondary"><MoreHorizontal size={15} /> More</Button><Button variant="primary"><MessageSquareText size={15} /> Add Comment</Button></>} />

    <section className="mission-stage-bar">{steps.map((step, index) => { const activeIndex = approval === "approved" ? 5 : 4; const complete = index < activeIndex; const active = index === activeIndex; return <div className={cn("mission-stage", complete && "mission-stage--complete", active && "mission-stage--active")} key={step}><span>{complete ? <Check size={11} /> : index + 1}</span><strong>{step}</strong>{index < steps.length - 1 ? <i /> : null}</div>; })}<div className="mission-stage-progress"><strong>{progress}%</strong><Progress value={progress} tone={approval === "approved" ? "success" : "warning"} /></div></section>

    <section className="mission-detail-grid">
      <div className="mission-context-column">
        <Card className="mission-overview-card"><CardHeader eyebrow="MISSION OVERVIEW" title={featuredMission.title} /><div className="mission-overview-hero"><span className="mission-overview-icon"><AlarmTriangle size={20} /></span><div><span className="mono">{turbine023.id} · MAIN BEARING</span><p>{featuredMission.summary}</p></div></div><div className="mission-overview-facts"><KeyValue label="Lead Agent" value={agents.find((item) => item.id === featuredMission.leadAgentId)?.shortName} /><KeyValue label="Participating Agents" value={`${featuredMission.agentIds.length} Agents`} /><KeyValue label="Evidence" value={`${featuredMission.evidenceIds.length} items`} /><KeyValue label="Target Resolution" value={new Date(featuredMission.targetResolutionAt).toLocaleString("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false })} /></div><div className="mission-next-action"><small>NEXT ACTION</small><strong>{approval === "approved" ? "生成工单并锁定作业资源" : featuredMission.nextAction}</strong></div></Card>

        <Card className="collaboration-card"><CardHeader eyebrow="PUBLIC EXECUTION TRACE" title="Agent Collaboration Graph" description="结构化协作过程 · 不展示隐藏推理" /><div className="agent-graph"><div className="agent-graph-row"><span className="graph-node graph-node--done"><Bot size={14} /><strong>SCADA</strong><small>anomaly data</small></span><i className="graph-edge"><em>evidence</em><ChevronRight size={13} /></i><span className="graph-node graph-node--done"><Activity size={14} /><strong>Vibration</strong><small>spectrum</small></span></div><div className="agent-graph-row"><span className="graph-node graph-node--done"><Sparkles size={14} /><strong>Diagnosis</strong><small>87% confidence</small></span><i className="graph-edge"><em>decision</em><ChevronRight size={13} /></i><span className="graph-node graph-node--active"><ShieldCheck size={14} /><strong>Review</strong><small>human gate</small></span></div><div className="agent-graph-row"><span className={cn("graph-node", approval === "approved" ? "graph-node--done" : "graph-node--waiting")}><UserCheck size={14} /><strong>Approval</strong><small>{approval}</small></span><i className="graph-edge"><em>approval</em><ChevronRight size={13} /></i><span className="graph-node graph-node--waiting"><Wrench size={14} /><strong>Work Order</strong><small>{workOrder ? workOrder.id : "pending"}</small></span></div></div><div className="graph-legend"><span><i className="graph-legend-dot graph-legend-dot--done" /> Complete</span><span><i className="graph-legend-dot graph-legend-dot--active" /> Active</span><span><i className="graph-legend-dot" /> Waiting</span></div></Card>

        <Card className="mission-agent-list"><CardHeader eyebrow="MISSION TEAM" title={`${missionAgents.length} Participating Agents`} /><div>{missionAgents.slice(0, 7).map((agent) => <button key={agent.id}><Avatar label={agent.shortName} tone={agent.layer === "decision" ? "teal" : agent.layer === "review" ? "amber" : "blue"} size="sm" /><span><strong>{agent.shortName}</strong><small>{agent.currentTask ?? agent.role}</small></span><StatusBadge value={agent.status} compact /></button>)}</div></Card>
      </div>

      <Card className="mission-timeline-card"><CardHeader eyebrow="LIVE ACTIVITY" title="Agent Activity Timeline" description="按时间记录 Tool、Evidence 与状态转换" action={<StatusBadge value="working" label="LIVE" tone="info" pulse compact />} /><div className="timeline-filter"><button className="active">All activity</button><button>Agents</button><button>Evidence</button><button>Reviews</button></div><div className="mission-timeline">{relatedEvents.map((event, index) => { const Icon = activityIcon[event.kind]; const agent = event.agentId ? agents.find((item) => item.id === event.agentId) : null; return <div className={cn("timeline-event", index === relatedEvents.length - 1 && "timeline-event--current")} key={event.id}><time>{formatTime(event.timestamp)}</time><span className={`timeline-event__node timeline-event__node--${event.outcome}`}><Icon size={13} /></span><div className="timeline-event__body"><div><span><Avatar label={agent?.shortName ?? event.actorLabel} tone={event.kind === "review" ? "amber" : "teal"} size="sm" /><span><strong>{agent?.shortName ?? event.actorLabel}</strong><small>{event.kind}</small></span></span><StatusBadge value={event.outcome} label={event.outcome.toUpperCase()} tone={event.outcome === "success" ? "success" : event.outcome === "attention" ? "warning" : event.outcome === "in-progress" ? "info" : "neutral"} compact /></div><h3>{event.title}</h3><p>{event.detail}</p>{event.evidenceIds.length ? <div className="timeline-evidence"><Link2 size={11} /> {event.evidenceIds.length} linked evidence</div> : null}</div></div>; })}</div></Card>

      <div className="decision-column">
        <Card className="current-decision-card"><CardHeader eyebrow="CURRENT DECISION" title="AI 推荐方案" description={`综合置信度 ${featuredDecision.confidencePercent}%`} /><div className="decision-recommendation"><span className="decision-recommendation__badge"><Sparkles size={14} /> RECOMMENDED · {recommended?.label}</span><h3>{recommended?.title}</h3><p>{recommended?.description}</p><div className="decision-tradeoffs"><div><small>安全风险</small><StatusBadge value={recommended?.safetyRisk ?? "medium"} label={(recommended?.safetyRisk ?? "medium").toUpperCase()} tone="warning" compact /></div><div><small>停机时间</small><strong>{recommended?.estimatedDowntimeHours} h</strong></div><div><small>预计成本</small><strong>¥{((recommended?.estimatedCostCny ?? 0) / 10000).toFixed(1)}万</strong></div><div><small>恶化概率</small><strong>{recommended?.deteriorationRiskPercent}%</strong></div></div><a href="/decisions">比较全部 {featuredDecision.alternatives.length} 个方案 <ArrowRight size={13} /></a></div>
          <div className="decision-evidence-summary"><span><FileSearch size={15} /></span><div><strong>{relatedEvidence.length} 项证据支持此判断</strong><small>SCADA · 振动频谱 · 历史案例 · 维护记录</small></div><a href="#evidence">查看</a></div>
        </Card>

        <Card className="weather-resource-card"><CardHeader eyebrow="EXECUTION READINESS" title="窗口与资源" /><div className="readiness-row"><span className="readiness-icon"><WeatherSun size={15} /></span><div><strong>{new Date(window?.startsAt ?? "2026-08-14").toLocaleDateString("zh-CN", { month: "short", day: "numeric" })} 作业窗口</strong><small>08:00–16:00 · 风速 {window?.windSpeedMps} m/s · 浪高 {window?.waveHeightM}m</small></div><StatusBadge value="suitable" label="适合" tone="success" compact /></div><div className="resource-readiness"><span><CheckCircle2 size={12} /> 维修班组</span><span><CheckCircle2 size={12} /> 运维船舶</span><span><CheckCircle2 size={12} /> 主轴承备件</span><span><CheckCircle2 size={12} /> 专用工具</span></div></Card>

        <Card className={cn("approval-card", approval !== "pending" && `approval-card--${approval}`)}><CardHeader eyebrow="HUMAN-IN-THE-LOOP" title="工程师审批" description="高风险动作必须经过人工授权" />{approval === "pending" ? <><div className="approval-gate"><div className="approval-flow"><span><Bot size={14} /><small>AI Recommendation</small></span><ChevronRight size={12} /><span><ShieldCheck size={14} /><small>Safety Review</small></span><ChevronRight size={12} /><span className="active"><UserCheck size={14} /><small>Human Approval</small></span></div><div className="approval-notice"><ShieldCheck size={15} /><p><strong>安全与工程审核已通过</strong><small>请确认风险、资源和天气窗口后执行。</small></p></div></div><textarea className="approval-comment" placeholder="填写审批意见（必填）…" aria-label="审批意见" defaultValue="同意按方案 B 降载运行，并于 8 月 14 日窗口执行主轴承检查。" /><div className="approval-actions"><Button variant="secondary" onClick={() => setApproval("rejected")}><X size={14} /> Reject</Button><Button variant="secondary" onClick={() => setApproval("revision")}><RefreshCcw size={14} /> Request Revision</Button><Button variant="primary" onClick={() => setApproval("approved")}><Check size={14} /> Approve</Button></div></> : <div className="approval-result"><span>{approval === "approved" ? <CheckCircle2 size={25} /> : approval === "revision" ? <RefreshCcw size={25} /> : <X size={25} />}</span><h3>{approval === "approved" ? "方案已批准并进入执行" : approval === "revision" ? "已请求修订" : "方案已拒绝"}</h3><p>{approval === "approved" ? "李明远已批准方案 B；工单 WO-20260823-017 已排程，作业资源正在最终确认。" : "操作已写入 Mission 审计日志。"}</p><small>李明远 · 值班总工程师 · 09:02</small><Button variant="secondary" onClick={() => setApproval("pending")}>重放审批环节</Button></div>}</Card>
      </div>
    </section>
  </AppShell>;
}
