"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Bot, CalendarClock, Check, CheckCircle2, ChevronDown, ClipboardCheck, Download, Filter, HardHat, MoreHorizontal, PackageCheck, Plus, Search, ShieldCheck, UserRound, Wrench, X } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/layout/page-header";
import { Button, Card, KeyValue, Progress } from "@/components/ui/primitives";
import { StatusBadge } from "@/components/data-display/status-badge";
import { featuredMission, workOrders } from "@/lib";
import type { WorkOrder, WorkOrderStatus } from "@/lib/types";
import { cn } from "@/lib/utils";

const statusLabels: Record<WorkOrderStatus, string> = { draft: "草稿", "pending-approval": "待审批", scheduled: "已排程", "in-progress": "执行中", paused: "暂停", completed: "已完成", closed: "已关闭" };

function WorkOrderDrawer({ workOrder, onClose }: { workOrder: WorkOrder; onClose: () => void }) {
  const completed = workOrder.tasks.filter((task) => task.completed).length;
  return <><button className="drawer-backdrop" onClick={onClose} aria-label="关闭工单详情" /><aside className="detail-drawer work-order-drawer" aria-label={`${workOrder.id} 工单详情`}>
    <header className="detail-drawer__header"><div><span className="eyebrow">WORK ORDER</span><h2>{workOrder.id}</h2><p>{workOrder.turbineId} · {workOrder.assignedTeam}</p></div><Button size="icon" variant="ghost" onClick={onClose} aria-label="关闭"><X size={18} /></Button></header>
    <div className="detail-drawer__status"><StatusBadge value={workOrder.status} label={statusLabels[workOrder.status]} tone={workOrder.status === "completed" || workOrder.status === "closed" ? "success" : workOrder.status === "in-progress" ? "info" : "warning"} /><StatusBadge value={workOrder.priority} label={workOrder.priority.toUpperCase()} tone={workOrder.priority === "critical" ? "critical" : workOrder.priority === "high" ? "warning" : "info"} /><span>{new Date(workOrder.plannedStart).toLocaleDateString("zh-CN")}</span></div>
    <section className="work-order-hero"><span><ClipboardCheck size={22} /></span><div><h3>{workOrder.issue}</h3><p>{workOrder.description}</p></div></section>
    {workOrder.createdByAgentId ? <div className="ai-generated-note"><Bot size={15} /><span><strong>由 Work Order Agent 自动生成</strong><small>来源 {workOrder.relatedMissionId} · 已通过 Safety Review</small></span><StatusBadge value="approved" label="AI VERIFIED" tone="info" compact /></div> : null}
    <section className="drawer-section"><h3>计划信息</h3><div className="key-value-list"><KeyValue label="计划开始" value={new Date(workOrder.plannedStart).toLocaleString("zh-CN")} /><KeyValue label="完成期限" value={new Date(workOrder.deadline).toLocaleString("zh-CN")} /><KeyValue label="预计时长" value={`${workOrder.estimatedDurationHours} 小时`} /><KeyValue label="责任班组" value={workOrder.assignedTeam} /><KeyValue label="关联 Mission" value={workOrder.relatedMissionId ?? "—"} mono /></div></section>
    <section className="drawer-section"><div className="drawer-section__title"><h3>任务清单</h3><span className="record-count">{completed} / {workOrder.tasks.length}</span></div><Progress value={(completed / Math.max(1, workOrder.tasks.length)) * 100} tone="info" /><div className="task-checklist">{workOrder.tasks.map((task) => <label key={task.id}><input type="checkbox" defaultChecked={task.completed} /><span><strong>{task.sequence}. {task.title}</strong>{task.completionNote ? <small>{task.completionNote}</small> : null}</span></label>)}</div></section>
    <section className="drawer-section"><h3>安全与 PPE</h3><div className="safety-procedure"><span className="safety-procedure__icon"><ShieldCheck size={15} /></span><div>{workOrder.safetyProcedures.map((procedure) => <span key={procedure}><Check size={11} /> {procedure}</span>)}</div></div><div className="ppe-chips">{workOrder.ppeRequirements.map((item) => <span key={item}><HardHat size={11} /> {item}</span>)}</div></section>
    <section className="drawer-section"><h3>备件与工具</h3><div className="part-list">{workOrder.spareParts.map((part) => <div key={part.partNumber}><span><PackageCheck size={14} /></span><div><strong>{part.name}</strong><small>{part.partNumber} · 需要 {part.quantity}</small></div><StatusBadge value={part.available >= part.quantity ? "available" : "shortage"} label={part.available >= part.quantity ? `可用 ${part.available}` : "库存不足"} tone={part.available >= part.quantity ? "success" : "critical"} compact /></div>)}</div><div className="tool-chip-grid">{workOrder.requiredTools.map((tool) => <span key={tool}><Wrench size={11} /> {tool}</span>)}</div></section>
    <footer className="detail-drawer__footer"><Button variant="secondary"><Download size={14} /> 导出 PDF</Button><Button variant="secondary"><UserRound size={14} /> 重新指派</Button><Button variant="primary"><CheckCircle2 size={14} /> 开始执行</Button></footer>
  </aside></>;
}

export function WorkOrderPage() {
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<"all" | WorkOrderStatus>("all");
  const [selected, setSelected] = useState<WorkOrder | null>(null);
  const filtered = useMemo(() => workOrders.filter((item) => (status === "all" || item.status === status) && `${item.id} ${item.turbineId} ${item.issue} ${item.assignedTeam}`.toLowerCase().includes(query.toLowerCase())), [query, status]);
  const featured = workOrders.find((item) => item.relatedMissionId === featuredMission.id) ?? workOrders[0];
  const counts = { pending: workOrders.filter((item) => item.status === "pending-approval").length, scheduled: workOrders.filter((item) => item.status === "scheduled").length, progress: workOrders.filter((item) => item.status === "in-progress").length, completed: workOrders.filter((item) => item.status === "completed" || item.status === "closed").length };

  return <AppShell activePath="/work-orders">
    <PageHeader eyebrow="运维执行" title="工单中心" description="从 AI 决策到人员、资源、安全流程和现场执行的闭环管理" breadcrumb={["运维执行", "工单中心"]} meta={<><StatusBadge value="in-progress" label={`${counts.progress} IN PROGRESS`} tone="info" pulse /><span className="page-meta-text">{counts.pending} 待审批 · {counts.scheduled} 已排程 · {counts.completed} 已完成</span></>} actions={<><Button variant="secondary"><Download size={15} /> 导出</Button><Button variant="primary"><Plus size={15} /> 创建工单</Button></>} />

    {featured ? <section className="featured-work-order"><div className="featured-work-order__tag"><Bot size={14} /><span><small>AI GENERATED · MISSION-2026-0823</small><strong>WT-023 主轴承检查工单已准备</strong></span></div><div className="featured-work-order__facts"><span><small>建议窗口</small><strong>8月14日 · 08:00</strong></span><span><small>预计时长</small><strong>{featured.estimatedDurationHours} 小时</strong></span><span><small>资源状态</small><strong className="success-text">全部就绪</strong></span></div><Button variant="primary" onClick={() => setSelected(featured)}>审核工单 <ArrowRight size={14} /></Button></section> : null}

    <section className="work-order-summary"><button onClick={() => setStatus("pending-approval")} className={cn(status === "pending-approval" && "active")}><span className="wo-summary-icon wo-summary-icon--warning"><ShieldCheck size={16} /></span><span><small>PENDING APPROVAL</small><strong>{counts.pending}</strong></span></button><button onClick={() => setStatus("scheduled")} className={cn(status === "scheduled" && "active")}><span className="wo-summary-icon wo-summary-icon--maintenance"><CalendarClock size={16} /></span><span><small>SCHEDULED</small><strong>{counts.scheduled}</strong></span></button><button onClick={() => setStatus("in-progress")} className={cn(status === "in-progress" && "active")}><span className="wo-summary-icon wo-summary-icon--info"><Wrench size={16} /></span><span><small>IN PROGRESS</small><strong>{counts.progress}</strong></span></button><button onClick={() => setStatus("all")} className={cn(status === "all" && "active")}><span className="wo-summary-icon wo-summary-icon--success"><CheckCircle2 size={16} /></span><span><small>COMPLETED</small><strong>{counts.completed}</strong></span></button></section>

    <section className="data-toolbar"><div className="search-field"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索工单、机组或班组…" aria-label="搜索工单" /></div><Button variant="secondary"><Filter size={14} /> Priority <ChevronDown size={12} /></Button><Button variant="secondary"><CalendarClock size={14} /> Planned Start <ChevronDown size={12} /></Button><span className="toolbar-result">{filtered.length} Work Orders</span><Button variant="ghost" onClick={() => { setStatus("all"); setQuery(""); }}>清除筛选</Button></section>

    <Card className="data-table-card"><div className="table-scroll"><table className="data-table"><thead><tr><th><input type="checkbox" aria-label="选择所有工单" /></th><th>Work Order ID</th><th>Wind Turbine</th><th>Issue</th><th>Priority</th><th>Status</th><th>Assigned Team</th><th>Created By</th><th>Related Mission</th><th>Planned Start</th><th>Deadline</th><th /></tr></thead><tbody>{filtered.map((item) => <tr className={cn(item.id === featured?.id && "row-featured")} key={item.id} onClick={() => setSelected(item)}><td onClick={(event) => event.stopPropagation()}><input type="checkbox" aria-label={`选择 ${item.id}`} /></td><td><strong className="mono">{item.id}</strong></td><td className="mono">{item.turbineId}</td><td><span className="alarm-title-cell"><strong>{item.issue}</strong><small>{item.description}</small></span></td><td><StatusBadge value={item.priority} label={item.priority.toUpperCase()} tone={item.priority === "critical" ? "critical" : item.priority === "high" ? "warning" : "info"} compact /></td><td><StatusBadge value={item.status} label={statusLabels[item.status]} tone={item.status === "completed" || item.status === "closed" ? "success" : item.status === "in-progress" ? "info" : item.status === "scheduled" ? "maintenance" : "warning"} compact /></td><td><span className="team-cell"><UserRound size={13} /> {item.assignedTeam}</span></td><td>{item.createdByAgentId ? <span className="ai-status-cell"><Bot size={13} /> AI Agent</span> : "人工创建"}</td><td className="mono">{item.relatedMissionId ?? "—"}</td><td>{new Date(item.plannedStart).toLocaleDateString("zh-CN")}</td><td>{new Date(item.deadline).toLocaleDateString("zh-CN")}</td><td><Button size="icon" variant="ghost" aria-label="更多"><MoreHorizontal size={14} /></Button></td></tr>)}</tbody></table></div><div className="table-pagination"><span>已选择 0 / {filtered.length} 行</span><span>第 1 页，共 3 页</span><div><Button size="sm" variant="secondary" disabled>上一页</Button><Button size="sm" variant="secondary">下一页</Button></div></div></Card>
    {selected ? <WorkOrderDrawer workOrder={selected} onClose={() => setSelected(null)} /> : null}
  </AppShell>;
}
